### ISSUE TITLE
Going Invis and Clothes don't save to body

### ISSUE THREAD

**Issue by HardAction** [RedEM-RP/redemrp_clothing#5]
When i open the menu and select all my clothes and save them, i immediately go invisible then after my character re-appears the clothes i just put on him aren't there, usually, the hat will stay. How would i fix this from happening? i have all the dependencies needed to run this script

**Comment by SirFreddie** [comment]
I had the same problem and fixed it using the commands /loadskin and /loadcloath until all my character got correctly loaded

**Comment by amakuu** [comment]
It depends what HDD/SSD drive you have.
/loadskin or /loadcloath should fix your problem.

/close
